### ISSUE TITLE
GPU not supported

### ISSUE THREAD

**Issue by snakeeater98** [n00mkrad/cupscale#74]
Hi,
whenever i try to upscale via ESRGAN (Pytorch) i get a error massage:

> Model: 4x_BSRGAN
Upscaling...
1 image-02721.png.png
Image loaded
Reloading model - model_path: C:\Users\Supra\Documents\Cupscale\models\ESRGAN\4x_BSRGAN.pth - last_model: None
Setting last_model to C:\Users\Supra\Documents\Cupscale\models\ESRGAN\4x_BSRGAN.pth
C:\Users\Supra\Documents\Cupscale\CupscaleData\bin\py\Lib\site-packages\torch\cuda\__init__.py:125: UserWarning:
NVIDIA GeForce RTX 3080 Ti with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA GeForce RTX 3080 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
> 
>   warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))

anyone know how to fix this ? 

thx, snake.

**Comment by snakeeater98** [comment]
Is this projekt still being worked on ?

If there is a way i can fix this myself id appreciate a answer.

**Comment by satsukiyatoshi** [comment]
Same bug here with a 3070ti, embeded python (dependency checker report it is ok).
Working great with my 1060gtx.

**Comment by snakeeater98** [comment]
The thing is, there is no error message.
What i gave u was the console output when trying to upscale a video.
Without console enabled its just stuck at "Loading ESTGAN (Pytorch)" on the progress bar.

**Comment by satsukiyatoshi** [comment]
Same here, no error messsage from cupscale, it's just get stuck waiting (with python.exe using about 1 full cpu core)

**Comment by snakeeater98** [comment]
When using the embedet python it does not work when installing python manualy it does not work, im out of ideas...

![Cupscale_lhUS4f8qCz](https://user-images.githubusercontent.com/64694429/147398074-fb1f4306-11f1-4a12-aaab-d336d48c6147.png)

**Comment by snakeeater98** [comment]
I dont understand what with model does, but .pth wasnt working. I somehow found the .bin and .param model, this works on the gpu to.

**Comment by teepean** [comment]
I had the same problem with the embedded Python but managed to fix it. My installation is on F-drive.

```
cd f:\Cupscale1.39.0f1\CupscaleData\bin\py

set PATH=F:\Cupscale1.39.0f1\CupscaleData\bin\py;%PATH%

python -m pip install torch==1.10.1+cu113 torchvision==0.11.2+cu113 torchaudio===0.10.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
```

**Comment by satsukiyatoshi** [comment]
@teepean
works perfectly here with my 3070ti, thanks !

**Comment by belidzs** [comment]
Same happened to me. Upgrading torch manually to include newer CUDA version fixed the issue

**Comment by RaaynML** [comment]
@teepean
This fixed it for me

If you have a system python in PATH already, you can also navigate into the `CupscaleData\bin\py `folder, open a cmd/powershell window within, and replace `python` with `.\python.exe` for the command to update the packages

**Comment by Lward95** [comment]
Running the command in @teepean 's comment gives me
Looking in links: https://download.pytorch.org/whl/cu113/torch_stable.html

> Requirement already satisfied: torch==1.10.1+cu113 in c:\users\lward\documents\cupscale 1.39.0f1\cupscaledata\bin\py\lib\site-packages (1.10.1+cu113)
> Requirement already satisfied: torchvision==0.11.2+cu113 in c:\users\lward\documents\cupscale 1.39.0f1\cupscaledata\bin\py\lib\site-packages (0.11.2+cu113)
> Requirement already satisfied: torchaudio===0.10.1+cu113 in c:\users\lward\documents\cupscale 1.39.0f1\cupscaledata\bin\py\lib\site-packages (0.10.1+cu113)
> Requirement already satisfied: typing-extensions in c:\users\lward\documents\cupscale 1.39.0f1\cupscaledata\bin\py\lib\site-packages (from torch==1.10.1+cu113) (4.2.0)
> Requirement already satisfied: pillow!=8.3.0,>=5.3.0 in c:\users\lward\documents\cupscale 1.39.0f1\cupscaledata\bin\py\lib\site-packages (from torchvision==0.11.2+cu113) (7.2.0)
> Requirement already satisfied: numpy in c:\users\lward\documents\cupscale 1.39.0f1\cupscaledata\bin\py\lib\site-packages (from torchvision==0.11.2+cu113) (1.19.1)
> 

Cupscale still showing 'Torch not found' 'OpenCV not found' 

Despite the fact i have installed both 


--- Reinstalling cupscale and running the command again has fixed it, Cupscale now works ?
